feat: add phrases
AlexandreL0pes/desmotiva_bot pull request #7
Opened 2021-10-03 17:41 UTC by dandankara

2021-10-04 23:42 UTC, AlexandreL0pes requested changes

2021-10-04 23:42 UTC, AlexandreL0pes commented on src/database/phrases.json
> +	},
Obrigado pela contribuição! Apenas um pequeno detalhe, consegue indentar essas frases aqui seguindo o padrão do arquivo? :nail_care:

2021-10-05 14:10 UTC, dandankara commented
acredito que a indentação esteja correta agora

2021-10-05 22:05 UTC, merged

2021-10-05 22:06 UTC, AlexandreL0pes reviewed
Muito obrigado! :rocket:

2021-10-05 22:08 UTC, AlexandreL0pes reviewed
:rocket: